-- 店铺资讯id
ALTER
TABLE S_ARTICLE
ADD COLUMN ARTICLE_BELONG_STORE_ID varchar(32)  DEFAULT NULL  COMMENT "店铺资讯所属店铺id" AFTER VIDEO_URL ;

-- 专访（访谈） 头像
ALTER
TABLE S_ARTICLE
ADD COLUMN INTERVIEWEE_PROFILE_URL varchar(255)  DEFAULT NULL  COMMENT "专访（访谈） 被采访者头像" AFTER ARTICLE_BELONG_STORE_ID;
-- 专访（访谈） 专访姓名
ALTER
TABLE S_ARTICLE
ADD COLUMN INTERVIEWEE_NAME  varchar(50)  DEFAULT NULL  COMMENT "专访（访谈） 被采访者姓名" AFTER INTERVIEWEE_PROFILE_URL;
-- 专访（访谈） 公司名称
ALTER
TABLE S_ARTICLE
ADD COLUMN INTERVIEWEE_STORE_NAME varchar(50)  DEFAULT NULL  COMMENT "专访（访谈） 被采访者所在公司名称" AFTER INTERVIEWEE_NAME;
-- 专访（访谈） 职位
ALTER
TABLE S_ARTICLE
ADD COLUMN INTERVIEWEE_POSITION varchar(50)  DEFAULT NULL  COMMENT "专访（访谈） 被采访者职位" AFTER INTERVIEWEE_STORE_NAME;