-- app资讯栏目整改
ALTER
TABLE S_COLUMN
ADD COLUMN SHOW_IN_APP TINYINT(1) NOT NULL DEFAULT 1  COMMENT "是否在APP端展示，默认为1，不展示" AFTER SPECIAL_FLAG;
ALTER
TABLE S_COLUMN
ADD COLUMN SHOW_NAME_IN_APP varchar(50)  DEFAULT NULL COMMENT "如果该栏目在APP端展示，展示的名称" AFTER SHOW_IN_APP ;

UPDATE S_COLUMN
SET SHOW_IN_APP = 0,
SHOW_NAME_IN_APP = '店铺资讯'
WHERE 1 = 1
AND AFFILIATION_COLUMN_NAME = '店铺';

UPDATE S_COLUMN
SET SHOW_IN_APP = 0,
SHOW_NAME_IN_APP = '专访'
WHERE 1 = 1
AND AFFILIATION_COLUMN_NAME = '访谈';

UPDATE S_COLUMN
SET SHOW_IN_APP = 0,
SHOW_NAME_IN_APP = '热门'
WHERE 1 = 1
AND AFFILIATION_COLUMN_NAME = '热门';

-- m站新机商品参数显示
UPDATE 
S_EQUIPMENT_PARAM_POOL
SET PARAM_NAME = REPLACE(PARAM_NAME,'（','(');
	UPDATE 
S_EQUIPMENT_PARAM_POOL
SET PARAM_NAME = REPLACE(PARAM_NAME,'）',')');