-- 经销商资讯的表数据存储由 S_STORE_CONTENT 迁移至 S_ARTICLE
-- 店铺资讯类型 
ALTER
TABLE S_ARTICLE
ADD COLUMN CONTENT_TYPE char(1)  DEFAULT NULL  COMMENT "（店铺资讯类型 ，0：资讯，1：活动）" AFTER ARTICLE_BELONG_STORE_ID ;

-- 店铺资讯上线状态标识
ALTER
TABLE S_ARTICLE
ADD COLUMN ONLINE_FLAG char(1)  DEFAULT NULL  COMMENT "上线状态标识（0 ： 下架， 1 ： 上架，2：草稿，3：强制下架）" AFTER CONTENT_TYPE ;

-- 平台资讯相关字段默认值设置
ALTER TABLE S_ARTICLE MODIFY column SHARE_FLAG char(1) not NULL DEFAULT '0' COMMENT "是否分享(0：分享，1不分享)" ;
ALTER TABLE S_ARTICLE MODIFY column COLLECT_FLAG char(1) not NULL DEFAULT '0' COMMENT "是否收藏（0：收藏，1：不收藏）";
ALTER TABLE S_ARTICLE MODIFY column DISCUSS_FLAG char(1) not NULL DEFAULT '0' COMMENT "是否评论(0：可评论，1：不可评论)";
ALTER TABLE S_ARTICLE MODIFY column DEL_FLAG char(1) not NULL DEFAULT '0' COMMENT "删除标记（0：未删除，1：已删除）";
ALTER TABLE S_ARTICLE MODIFY column PUSH_FLAG char(1) not NULL DEFAULT '0' COMMENT "(推送至首页标识，0：不推送，1：推送)";