ALTER TABLE T_TIPS 
ADD COLUMN PUSH_DEVICE CHAR(1) COMMENT '推送设备：0:不向APP推送，1所有设备，2安卓，3IOS' NOT NULL DEFAULT '0' AFTER ID,
ADD COLUMN NOTIFICATION_TITLE VARCHAR(255) COMMENT '消息推送时的标题：如灜沣工程机械' NOT NULL DEFAULT '灜沣工程机械' AFTER TIPS_COUNT,
ADD COLUMN PUSH_TIME DATETIME COMMENT '推送时间' NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER CREATED_TIME,
ADD COLUMN PUSH_TIME_TYPE CHAR(1) COMMENT '推送时间类型：1：立即推送，2：定时推送' NOT NULL DEFAULT '1' AFTER PUSH_TIME,
ADD COLUMN PUSH_FLAG CHAR(1) COMMENT '是否已推送：0：已推送，1：未推送' NOT NULL DEFAULT '0' AFTER PUSH_TIME_TYPE;