ALTER TABLE T_LIVE_SUBSIDIARY 
ADD COLUMN LIVE_SUBJECT_ADDRESS VARCHAR(255) COMMENT '直播对应的专题web地址' NOT NULL DEFAULT 'www.yingfeng365.com' AFTER LIVE_ADDRESS,
ADD COLUMN LIVE_SUBJECT_ADDRESS_APP VARCHAR(255) COMMENT '直播对应的专题app地址' NOT NULL DEFAULT 'www.yingfeng365.com' AFTER LIVE_ADDRESS_APP,
ADD COLUMN COVER_ID CHAR(32) COMMENT '封面图片的地址附件id' AFTER INTERVAL_TIME