ALTER TABLE S_BANNER_MANAGE ADD JUMP_LINK_TYPE CHAR(1)  COMMENT '0：二手、1：新机、2：资讯、3：其他、4：专题';
UPDATE S_BANNER_MANAGE SET JUMP_LINK_TYPE = '3';
ALTER TABLE S_BANNER_MANAGE MODIFY JUMP_LINK_TYPE  CHAR(1)  NOT NULL DEFAULT '3' COMMENT '0：二手、1：新机、2：资讯、3：其他、4：专题';