-- 索引脚本
-- author : pengc
-- date : 2017/01/30

-- 示例
-- 索引名称：idx_+名称

-- 添加
-- CREATE INDEX idx_name ON table_name (column_list)
-- CREATE UNIQUE INDEX idx_name ON table_name (column_list)

-- 删除
-- DROP INDEX idx_name ON talbe_name

-- 查询
-- show index from tblname;

-- 设备管理

-- S_BRANDS(品牌表)
CREATE INDEX idx_id ON S_BRANDS(ID);
CREATE INDEX idx_chinese ON S_BRANDS(CHINESE_NAME);
CREATE INDEX idx_alias_name ON S_BRANDS(ALIAS_NAME);

-- S_BRAND_TYPE(品牌类型表)
CREATE INDEX idx_brand_id ON S_BRAND_TYPE(BRAND_ID);

-- S_BRAND_EQUIPMENT_CATEGORY（所属品类表）
CREATE INDEX idx_brand_id ON S_BRAND_EQUIPMENT_CATEGORY(BRAND_ID);
CREATE INDEX idx_brand_type_id ON S_BRAND_EQUIPMENT_CATEGORY(BRAND_TYPE_ID);
CREATE INDEX idx_category_code ON S_BRAND_EQUIPMENT_CATEGORY(CATEGORY_CODE);

-- S_BRAND_HOT(热门品牌)
CREATE INDEX idx_brand_id ON S_BRAND_HOT(BRAND_ID);
CREATE INDEX idx_business_type_code ON S_BRAND_HOT(BUSINESS_TYPE_CODE);

-- S_EQUIPMENT_PARAM_TYPE（设备分类表）
CREATE INDEX idx_id ON S_EQUIPMENT_PARAM_TYPE(ID);
CREATE INDEX idx_parent_id ON S_EQUIPMENT_PARAM_TYPE(PARENT_ID);
CREATE INDEX idx_param_code ON S_EQUIPMENT_PARAM_TYPE(PARAM_CODE);

-- S_STORE_EQUIPMENT_PARAM（店铺设备常量表）
CREATE INDEX idx_parent_id ON S_STORE_EQUIPMENT_PARAM(PARENT_ID);
CREATE INDEX idx_parent_code ON S_STORE_EQUIPMENT_PARAM(PARENT_CODE);
CREATE INDEX idx_param_code ON S_STORE_EQUIPMENT_PARAM(PARAM_CODE);

-- S_EQUIPMENT_PARAM_POOL（参数池）
CREATE INDEX idx_parent_id ON S_EQUIPMENT_PARAM_POOL(PARENT_ID);
CREATE INDEX idx_parent_code ON S_EQUIPMENT_PARAM_POOL(PARENT_CODE);
CREATE INDEX idx_param_code ON S_EQUIPMENT_PARAM_POOL(PARAM_CODE);

-- S_PAGE_PARAM_CONFIG（页面参数配置）
CREATE INDEX idx_equipment_type_code ON S_PAGE_PARAM_CONFIG(EQUIPMENT_TYPE_CODE);
CREATE INDEX idx_param_code ON S_PAGE_PARAM_CONFIG(PARAM_CODE);

-- S_PARAM_LABEL_VALUE（参数标签属性值表）
CREATE INDEX idx_equipment_type_code ON S_PARAM_LABEL_VALUE(EQUIPMENT_TYPE_CODE);
CREATE INDEX idx_param_code ON S_PARAM_LABEL_VALUE(PARAM_CODE);
CREATE INDEX idx_parent_id ON S_PARAM_LABEL_VALUE(PARENT_ID);

-- S_EQUIPMENT（设备表）
CREATE INDEX idx_equipment_sku ON S_EQUIPMENT(EQUIPMENT_SKU);
CREATE INDEX idx_first_type_code ON S_EQUIPMENT(FIRST_TYPE_CODE);
CREATE INDEX idx_two_type_code ON S_EQUIPMENT(TWO_TYPE_CODE);
CREATE INDEX idx_brand_id ON S_EQUIPMENT(BRAND_ID);

-- S_EQUIPMENT_PARAM（设备参数表）
CREATE INDEX idx_equipment_id ON S_EQUIPMENT_PARAM(EQUIPMENT_ID);
CREATE INDEX idx_param_label_id ON S_EQUIPMENT_PARAM(PARAM_LABEL_ID);
CREATE INDEX idx_param_label_code ON S_EQUIPMENT_PARAM(PARAM_LABEL_CODE);

-- S_EQUIPMENT_FILE（设备文件表）
CREATE INDEX idx_equipment_id ON S_EQUIPMENT_FILE(EQUIPMENT_ID);

-- S_EQUIPMENT_ATTACHMENT（设备文件关联表）
CREATE INDEX idx_attachment_id ON S_EQUIPMENT_ATTACHMENT(ATTACHMENT_ID);
CREATE INDEX idx_equipment_file_id ON S_EQUIPMENT_ATTACHMENT(EQUIPMENT_FILE_ID);


-- 店铺
-- S_STORE_INFO（店铺基础信息表）
CREATE INDEX idx_customer_id ON S_STORE_INFO(CUSTOMER_ID);
CREATE INDEX idx_company_name ON S_STORE_INFO(COMPANY_NAME);
CREATE INDEX idx_card_id ON S_STORE_INFO(CARD_ID);
CREATE INDEX idx_mobile ON S_STORE_INFO(MOBILE);

-- S_STORE_INFO_AUDIT(店铺基础信息审核表)
CREATE INDEX idx_customer_id ON S_STORE_INFO_AUDIT(CUSTOMER_ID);
CREATE INDEX idx_company_name ON S_STORE_INFO_AUDIT(COMPANY_NAME);
CREATE INDEX idx_card_id ON S_STORE_INFO_AUDIT(CARD_ID);
CREATE INDEX idx_mobile ON S_STORE_INFO_AUDIT(MOBILE);

-- S_STORE_MANAGE_BRAND（店铺经营品牌表）
CREATE INDEX idx_store_id ON S_STORE_MANAGE_BRAND(STORE_ID);
CREATE INDEX idx_brands_id ON S_STORE_MANAGE_BRAND(BRANDS_ID);

-- S_STORE_MANAGE_MODEL（店铺经营机型）
CREATE INDEX idx_manage_brand_id ON S_STORE_MANAGE_MODEL(MANAGE_BRAND_ID);

-- S_STORE_MANAGE_AREA（店铺经营地区）
CREATE INDEX idx_manage_brand_id ON S_STORE_MANAGE_AREA(MANAGE_BRAND_ID);
CREATE INDEX idx_store_id ON S_STORE_MANAGE_AREA(STORE_ID);

-- S_STORE_AUDIT_LOG（店铺审核日志表）
CREATE INDEX idx_store_id ON S_STORE_AUDIT_LOG(STORE_ID);

-- S_ATTACHMENT_RELATE（附件文件关联表）
CREATE INDEX idx_attachment_id ON S_ATTACHMENT_RELATE(ATTACHMENT_ID);
CREATE INDEX idx_relevance_id ON S_ATTACHMENT_RELATE(RELEVANCE_ID);

-- S_STORE_BUSINESS_STATUS（店铺业务状态表）
CREATE INDEX idx_store_id ON S_STORE_BUSINESS_STATUS(STORE_ID);

-- S_GOODS（商品信息）
CREATE INDEX idx_store_id ON S_GOODS(STORE_ID);
CREATE INDEX idx_brand_id ON S_GOODS(BRAND_ID);
CREATE INDEX idx_equipment_model ON S_GOODS(EQUIPMENT_MODEL);

-- S_HOT_GOODS（热销新机）
CREATE INDEX idx_goods_id ON S_HOT_GOODS(GOODS_ID);

-- S_EQUIPMENT_FEEDBACK（设备反馈）
CREATE INDEX idx_store_id ON S_EQUIPMENT_FEEDBACK(STORE_ID);
CREATE INDEX idx_brand_id ON S_EQUIPMENT_FEEDBACK(BRAND_ID);

-- S_GOODS_IMAGE（商品图片表）
CREATE INDEX idx_store_id ON S_GOODS_IMAGE(STORE_ID);
CREATE INDEX idx_goods_id ON S_GOODS_IMAGE(GOODS_ID);
CREATE INDEX idx_attachment_id ON S_GOODS_IMAGE(ATTACHMENT_ID);
CREATE INDEX idx_relevance_id ON S_GOODS_IMAGE(RELEVANCE_ID);

-- S_STORE_INFORMATION（店铺资讯表）
CREATE INDEX idx_store_id ON S_STORE_INFORMATION(STORE_ID);

-- S_STORE_ACTIVITY（店铺活动表）
CREATE INDEX idx_store_id ON S_STORE_ACTIVITY(STORE_ID);
CREATE INDEX idx_model_id ON S_STORE_ACTIVITY(MODEL_ID);

-- S_STORE_BANNER（banner管理）
CREATE INDEX idx_store_id ON S_STORE_BANNER(STORE_ID);
CREATE INDEX idx_article_id ON S_STORE_BANNER(ARTICLE_ID);

-- 首页

-- S_BANNER_MANAGE（平台banner管理）
CREATE INDEX idx_banner_title ON S_BANNER_MANAGE(BANNER_TITLE);

-- S_SITE_BANNER_RELEVANCE（站点和banner关联表）
CREATE INDEX idx_site_id ON S_SITE_BANNER_RELEVANCE(SITE_ID);
CREATE INDEX idx_banner_id ON S_SITE_BANNER_RELEVANCE(BANNER_ID);
CREATE INDEX idx_banner_type_id ON S_SITE_BANNER_RELEVANCE(BANNER_TYPE_ID);

-- S_BANNER_TYPE（banner类型表）
CREATE INDEX idx_banner_id ON S_BANNER_TYPE(BANNER_ID);

-- S_SECOND_HAND_EQUIPMENT（二手设备）
CREATE INDEX idx_equipment_name ON S_SECOND_HAND_EQUIPMENT(EQUIPMENT_NAME);

-- S_SYSTEM_NAV_MANAGE（导航管理）
CREATE INDEX idx_nav_name ON S_SYSTEM_NAV_MANAGE(NAV_NAME);
CREATE INDEX idx_parent_id ON S_SYSTEM_NAV_MANAGE(PARENT_ID);

-- S_ADVER_MANAGE（广告位管理）
CREATE INDEX idx_adver_title ON S_ADVER_MANAGE(ADVER_TITLE);

-- S_ADVER_FLOOR（楼层广告位）
CREATE INDEX idx_adver_id ON S_ADVER_FLOOR(ADVER_ID);

-- S_SITE_ADVER_RELEVANCE（站点和广告关联表）
CREATE INDEX idx_site_id ON S_SITE_ADVER_RELEVANCE(SITE_ID);
CREATE INDEX idx_adver_id ON S_SITE_ADVER_RELEVANCE(ADVER_ID);

-- S_ADVICE_FEEDBACK（用户意见反馈）
CREATE INDEX idx_user_name ON S_ADVICE_FEEDBACK(USER_NAME);
CREATE INDEX idx_mobile ON S_ADVICE_FEEDBACK(MOBILE);

-- S_PLATFORM_VIDEO（平台视频）
CREATE INDEX idx_video_title ON S_PLATFORM_VIDEO(VIDEO_TITLE);

-- S_STORE_CLAIM_USER（店铺认领用户）
CREATE INDEX idx_store_id ON S_STORE_CLAIM_USER(STORE_ID);
CREATE INDEX idx_customer_id ON S_STORE_CLAIM_USER(CUSTOMER_ID);
CREATE INDEX idx_mobile ON S_STORE_CLAIM_USER(MOBILE);

-- S_ENQUIRY_MANAGE（询价管理）
CREATE INDEX idx_store_id ON S_ENQUIRY_MANAGE(STORE_ID);
CREATE INDEX idx_mobile ON S_ENQUIRY_MANAGE(MOBILE);
CREATE INDEX idx_equipment_id ON S_ENQUIRY_MANAGE(EQUIPMENT_ID);

-- S_LOAN_MANAGE（贷款管理）
CREATE INDEX idx_customer_name ON S_LOAN_MANAGE(CUSTOMER_NAME);
CREATE INDEX idx_mobile ON S_LOAN_MANAGE(MOBILE);

-- 系统

-- T_USER（用户表）
CREATE INDEX idx_login_name ON T_USER(LOGIN_NAME);
CREATE INDEX idx_real_name ON T_USER(REAL_NAME);

-- T_USER_ROLE（用户角色关联表）
CREATE INDEX idx_user_id ON T_USER_ROLE(USER_ID);
CREATE INDEX idx_role_id ON T_USER_ROLE(ROLE_ID);

-- T_ROLE（角色表）
CREATE INDEX idx_role_code ON T_ROLE(ROLE_CODE);

-- T_ROLE_MENU（角色菜单关联表）
CREATE INDEX idx_role_id ON T_ROLE_MENU(ROLE_ID);
CREATE INDEX idx_menu_id ON T_ROLE_MENU(MENU_ID);

-- T_MENU（菜单表）
CREATE INDEX idx_parent_id ON T_MENU(PARENT_ID);

-- T_MENU_BUSINESS_DIVISION（菜单业务划分表）
CREATE INDEX idx_menu_id ON T_MENU_BUSINESS_DIVISION(MENU_ID);
CREATE INDEX idx_business_type_code ON T_MENU_BUSINESS_DIVISION(BUSINESS_TYPE_CODE);

-- S_CUSTOMER_BUSINESS_MENU（用户与业务菜单关联表）
CREATE INDEX idx_customer_id ON S_CUSTOMER_BUSINESS_MENU(CUSTOMER_ID);
CREATE INDEX idx_business_id ON S_CUSTOMER_BUSINESS_MENU(MENU_BUSINESS_ID);

-- S_ROLE（店铺角色表）
CREATE INDEX idx_role_code ON S_ROLE(ROLE_CODE);

-- S_ROLE_MENU（店铺角色菜单关联表）
CREATE INDEX idx_role_id ON S_ROLE_MENU(ROLE_ID);
CREATE INDEX idx_menu_id ON S_ROLE_MENU(MENU_ID);

-- T_PROVINCE（省份表）
CREATE INDEX idx_province_name ON T_PROVINCE(PROVINCE_NAME);
CREATE UNIQUE INDEX idx_uqe_province_code ON T_PROVINCE(PROVINCE_CODE);
CREATE INDEX idx_spell ON T_PROVINCE(SPELL);

-- T_CITY（城市表）
CREATE INDEX idx_city_name ON T_CITY(CITY_NAME);
CREATE UNIQUE INDEX idx_uqe_city_code ON T_CITY(CITY_CODE);
CREATE INDEX idx_spell ON T_CITY(SPELL);
CREATE INDEX idx_province_code ON T_CITY(PROVINCE_CODE);

-- T_DISTRICT（区县表）
CREATE INDEX idx_district_name ON T_DISTRICT(DISTRICT_NAME);
CREATE UNIQUE INDEX idx_uqe_district_code ON T_DISTRICT(DISTRICT_CODE);
CREATE INDEX idx_spell ON T_DISTRICT(SPELL);
CREATE INDEX idx_city_code ON T_DISTRICT(CITY_CODE);

-- T_PARAM（系统参数字典表）
CREATE INDEX idx_parent_id ON T_PARAM(PARENT_ID);
CREATE INDEX idx_name ON T_PARAM(NAME);
-- CREATE UNIQUE INDEX idx_uqe_code ON T_PARAM(CODE);
CREATE INDEX idx_code ON T_PARAM(CODE);

-- T_SITE_MASTER（分站点管理）
CREATE INDEX idx_site_name ON T_SITE_MASTER(SITE_NAME);

-- T_SITE_AREA（站点地区）
CREATE INDEX idx_site_id ON T_SITE_AREA(SITE_ID);
CREATE INDEX idx_province ON T_SITE_AREA(PROVINCE);
CREATE INDEX idx_city ON T_SITE_AREA(CITY);
CREATE INDEX idx_county ON T_SITE_AREA(COUNTY);

-- T_SITE_STORE_RELEVANCE（站点和店铺关联表）
CREATE INDEX idx_site_id ON T_SITE_STORE_RELEVANCE(SITE_ID);
CREATE INDEX idx_site_area_id ON T_SITE_STORE_RELEVANCE(SITE_AREA_ID);
-- CREATE INDEX idx_store_id ON T_SITE_STORE_RELEVANCE(STORE_ID);
-- 表字段需要更新(shop_id -> store_id)
CREATE INDEX idx_shop_id ON T_SITE_STORE_RELEVANCE(shop_id);

-- 会员
-- S_CUSTOMER（会员表）
CREATE INDEX idx_user_name ON S_CUSTOMER(USER_NAME);
CREATE INDEX idx_nick_name ON S_CUSTOMER(NICK_NAME);
CREATE INDEX idx_mobile ON S_CUSTOMER(MOBILE);
CREATE INDEX idx_password ON S_CUSTOMER(PASSWORD);

-- S_CUSTOMER_BASE_INFO（会员基础信息表）
CREATE INDEX idx_customer_id ON S_CUSTOMER_BASE_INFO(CUSTOMER_ID);
CREATE INDEX idx_card_id ON S_CUSTOMER_BASE_INFO(CARD_ID);
CREATE INDEX idx_email ON S_CUSTOMER_BASE_INFO(EMAIL);
CREATE INDEX idx_mobile ON S_CUSTOMER_BASE_INFO(MOBILE);
CREATE INDEX idx_phone ON S_CUSTOMER_BASE_INFO(PHONE);

-- S_CUSTOMER_BUSINESS_INFO（会员业务信息）
CREATE INDEX idx_customer_id ON S_CUSTOMER_BUSINESS_INFO(CUSTOMER_ID);

-- S_CUSTOMER_LOGIN_LOG（登录日志表）
CREATE INDEX idx_mobile ON S_CUSTOMER_LOGIN_LOG(MOBILE);

-- S_STORE_INFO（店铺正式表）
CREATE INDEX idx_status ON S_STORE_INFO(OPERATE_STATUS, DEL_FLAG);
